version: '3.7'

services:
  jenkins:
    build: .
    container_name: jenkins
    restart: always
    ports:
      - "8585:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      JENKINS_USER: admin
      JENKINS_PASSWORD: Openstack#12345  
volumes:
  jenkins_home:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.96,rw,nfsvers=4"
      device: ":/nfs-share/jenkins/jenkins_home"
